name: CI

on: [push, pull_request]

jobs:
  run:
    name: "Build using Racket '${{ matrix.racket-version }}' (${{ matrix.racket-variant }})"
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.xfail == 'yes' }}
    strategy:
      fail-fast: false
      matrix:
        racket-version: ["6.7", "6.8", "6.9", "6.11", "6.12", "7.0", "7.1", "7.2", "7.3", "7.4", "7.5", "7.6", "7.7", "7.8", "7.9", "8.0", "8.1", "current"]
        racket-variant: ["BC", "CS"]
        # CS builds are only provided for versions 7.4 and up so avoid
        # running the job for prior versions.
        exclude:
          - {racket-version: "6.6",    racket-variant: "CS"}
          - {racket-version: "6.7",    racket-variant: "CS"}
          - {racket-version: "6.8",    racket-variant: "CS"}
          - {racket-version: "6.9",    racket-variant: "CS"}
          - {racket-version: "6.10.1", racket-variant: "CS"}
          - {racket-version: "6.11",   racket-variant: "CS"}
          - {racket-version: "6.12",   racket-variant: "CS"}
          - {racket-version: "7.0",    racket-variant: "CS"}
          - {racket-version: "7.1",    racket-variant: "CS"}
          - {racket-version: "7.2",    racket-variant: "CS"}
          - {racket-version: "7.3",    racket-variant: "CS"}
        include:
          - {racket-version: "6.7",     racket-variant: "BC", xfail: "yes"}
          - {racket-version: "7.7",     racket-variant: "CS", xfail: "yes"}
          - {racket-version: "7.8",     racket-variant: "CS", xfail: "yes"}
          - {racket-version: "7.9",     racket-variant: "CS", xfail: "yes"}
          - {racket-version: "current", racket-variant: "BC", xfail: "yes"}
          - {racket-version: "current", racket-variant: "CS", xfail: "yes"}
    env:
      DISPLAY: :99

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - uses: Bogdanp/setup-racket@v0.11
      with:
        distribution: 'full'
        version: ${{ matrix.racket-version }}
        variant: ${{ matrix.racket-variant }}

    - name: Install package and its dependencies
      run: raco pkg install --deps search-auto https://github.com/mbutterick/br-parser-tools.git?path=br-parser-tools-lib
    - name: install brag
      run: raco pkg install --deps search-auto https://github.com/mbutterick/brag.git?path=brag
    - name: install br-macro
      run: raco pkg install --deps search-auto https://github.com/mbutterick/beautiful-racket.git?path=beautiful-racket-macro
    - name: install br lib
      run: raco pkg install --deps search-auto https://github.com/mbutterick/beautiful-racket.git?path=beautiful-racket-lib
    - name: install br demo
      run: raco pkg install --deps search-auto https://github.com/mbutterick/beautiful-racket.git?path=beautiful-racket-demo
    - name: install br
      run: raco pkg install --deps search-auto https://github.com/mbutterick/beautiful-racket.git?path=beautiful-racket

    - name: Start virtual framebuffer
      run: Xvfb "$DISPLAY" -screen 0 1280x1024x24 &

    - name: Run the brm tests
      run: raco test -p beautiful-racket-macro
    - name: Run the lib tests
      run: raco test -p beautiful-racket-lib
    - name: Run the demo tests
      run: raco test -p beautiful-racket-demo
    - name: Run the br tests
      run: raco test -p beautiful-racket
